#!/bin/bash

# Get the list of Wi-Fi networks
SSID=$(nmcli device wifi list | dmenu -i -p "Select Wi-Fi Network:" | awk '{print $2}')

# If an SSID was selected
if [[ -n "$SSID" ]]; then
    # Check if already connected to the selected SSID
    CONNECTED_SSID=$(nmcli -t -f active,ssid device wifi | grep "^yes" | awk -F ':' '{print $2}')
    
    if [[ "$CONNECTED_SSID" != "$SSID" ]]; then
        # Prompt for the Wi-Fi password using dmenu (password will be masked)
        PASSWORD=$(dmenu -p "Enter Password for $SSID:" -l 0 -password)

        # Run the nmcli command to connect to the network using the entered password
        echo "$PASSWORD" | sudo nmcli device wifi connect "$SSID" password "$(cat)"
    fi
fi
